openapi: 3.0.0
info:
  title: ProduktDemo API
  description: API for managing products in the ProduktDemo application.
  version: 1.0.0
servers:
  - url: http://localhost:8080
    description: Local server

paths:
  /api/produkte:
    get:
      summary: Get all products
      operationId: getAllProdukts
      responses:
        '200':
          description: A list of products
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Produkt'
    post:
      summary: Create a new product
      operationId: createProdukt
      requestBody:
        description: The product to create
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Produkt'
      responses:
        '201':
          description: The created product
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Produkt'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                type: string
                example: "Invalid product data"

  /api/produkte/{id}:
    get:
      summary: Get a product by ID
      operationId: getProduktById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: The requested product
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Produkt'
        '404':
          description: Product not found
          content:
            application/json:
              schema:
                type: string
                example: "Produkt mit ID {id} nicht gefunden"
    delete:
      summary: Delete a product by ID
      operationId: deleteProduktById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '204':
          description: Product deleted successfully
    put:
      summary: Update a product by ID
      operationId: updateProdukt
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        description: The product data to update
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Produkt'
      responses:
        '200':
          description: The updated product
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Produkt'
        '404':
          description: Product not found
          content:
            application/json:
              schema:
                type: string
                example: "Produkt mit ID {id} nicht gefunden"

components:
  schemas:
    Produkt:
      type: object
      properties:
        id:
          type: integer
          format: int64
          readOnly: true
        name:
          type: string
        price:
          type: number
          format: double
        description:
          type: string
        category:
          type: string
        stock:
          type: integer
      required:
        - name
        - price
        - description
        - category
        - stock
